template = "https://github.com/giellalt/template-lang-und"
rev_id = 337
template_sha = "1c2fffaa917a9c6f340d9887d554609eb561ade6"

[replacements]
__GLOTTOLOG_ID__ = "norw1262"
__REPO__ = "lang-nno-x-ext-apertium"
__UND2C__ = "nn"
__UNDEFINED__ = "Norwegian Nynorsk"
__UND__ = "nno"
