template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "norw1262"
__REPO__ = "lang-nno-x-ext-apertium"
__UND2C__ = "nn"
__UNDEFINED__ = "Norwegian Nynorsk"
__UND__ = "nno"
