template = "https://github.com/giellalt/template-lang-und"
rev_id = 315
template_sha = "7bf6bff34d74d9a0e529dc6e82a8e0408e104534"

[replacements]
__GLOTTOLOG_ID__ = "norw1262"
__REPO__ = "lang-nno-x-ext-apertium"
__UND2C__ = "nn"
__UNDEFINED__ = "Norwegian Nynorsk"
__UND__ = "nno"
